name: Publish Single Markdown to Pages

# Run when the target MD or assets change, or when this workflow is updated
on:
  push:
    paths:
      - './iceberg-prediction-whitepaper-v2.md'
      - 'assets/**'
      - '.github/workflows/publish-single-markdown-github-pages.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout full history (needed to create/commit to gh-pages)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0                                      

      # 2. Prepare the public directory
      - name: Prepare Pages content
        run: |
          mkdir public
          cp iceberg-prediction-whitepaper-v2.md public/index.md             # Rename to index.md
          cp -R assets public/assets                      # Copy images

      # 3. Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}       # Auth token
          publish_branch: gh-pages                        # Target branch
          publish_dir: ./public                           

      # 4. (Optional) Clean up local public folder
      - name: Cleanup
        if: always()
        run: |
          rm -rf public
