name: Publish Single Markdown to Pages

on:
  push:
    paths:
      - '/iceberg-prediction-whitepaper-v2.md'
      - 'assets/**'
      - '.github/workflows/publish-single-markdown-github-pages.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout full history so we can create gh-pages
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Build the 'public' folder
      - name: Prepare Pages content
        run: |
          mkdir public
          cp iceberg-prediction-whitepaper-v2.md public/index.md
          cp -R assets public/assets

      # 3. Deploy to gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public

      # 4. Configure GitHub Pages via API
      - name: Enable GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.switcheroo-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"source":{"branch":"gh-pages","path":"/"}}'

      # 5. Clean up
      - name: Cleanup
        if: always()
        run: rm -rf public
