name: Test MyST GitHub Pages Deploy

on:
  push:
    branches:
      - test-workflow
  workflow_dispatch:

env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and Jupyter
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install system dependencies from .binder/apt.txt
        run: |
          sudo apt-get update
          < .binder/apt.txt xargs sudo apt-get install -y

      - name: Run Binder postBuild
        run: bash .binder/postBuild

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install npm dependencies and build components
        run: |
          npm install --force
          node build-components.mjs
          
      - name: Install MyST Markdown CLI
        run: npm install -g mystmd

      - name: Install Typst
        run: |
          curl -L -o typst.tar.xz \
            https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst.tar.xz
          mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/

      - name: Prepare Directories
        run: mkdir -p exports

      - name: Build PDF Assets (with execution)
        run: |
          myst build iceberg-prediction-whitepaper-v2.md --pdf --execute
          myst build index.md --pdf --execute

      - name: Build HTML Assets (with execution)
        run: myst build --execute --html

      - name: Ensure PDFs are in HTML output
        run: |
          mkdir -p _build/html/exports
          cp exports/*.pdf _build/html/exports/

      - name: Copy project assets into build output
        run: |
          if [ -d "assets" ]; then
            cp -R assets _build/html/assets
          fi

      # Upload artifacts but don't deploy
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: _build/html
